# MySQL 테스트 데이터베이스 세팅(AWS EC2)
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://lab-db.cfdztcppxxdo.ap-northeast-2.rds.amazonaws.com/nsl_test?serverTimezone=UTC&characterEncoding=UTF-8
        username: knunslabdbadmin
        password: labdbpassword22
logging:
    level:
        root: DEBUG
        