# MySQL 데이터베이스 세팅(local)
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://lab-db.cfdztcppxxdo.ap-northeast-2.rds.amazonaws.com/nsl?serverTimezone=UTC&characterEncoding=UTF-8
        username: knunslabdbadmin
        password: labdbpassword22
    mail:
        host: smtp.naver.com 
        port: 465
        username: 수정필요
        password: 수정필요
        properties:
            mail.smtp.auth: true
            mail.smtp.ssl.enable: true
            mail.smtp.ssl.trust: smtp.naver.com

logging:
    level:
        root: DEBUG